const NOTIFICATION_TYPES = Object.freeze({
  JOB_APPLIED: 'JOB_APPLIED',
  APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
  APPLICATION_STATUS_UPDATE: 'APPLICATION_STATUS_UPDATE',
  JOB_POSTED: 'JOB_POSTED',
  PROFILE_VIEWED: 'PROFILE_VIEWED',
  WELCOME: 'WELCOME',
  GENERAL: 'GENERAL',
  NEW_USER: 'NEW_USER',
  NEW_APPLICATION: 'NEW_APPLICATION',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_RENEWAL_INITIATED: 'SUBSCRIPTION_RENEWAL_INITIATED',
  SUBSCRIPTION_RENEWAL_FAILED: 'SUBSCRIPTION_RENEWAL_FAILED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_RENEWING_SOON: 'SUBSCRIPTION_RENEWING_SOON'
});

module.exports = {
  NOTIFICATION_TYPES
};
